# .github/workflows/ci.yml

name: CI/CD Pipeline

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    script:
      - docker build -t classifier .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: make test