# .github/workflows/ci.yml

name: CI/CD Pipeline

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ main ]

jobs:
  prereqs:
    steps:
      - name: Install Prereqs
        run: make prereqs

  build:
    needs: prereqs
    steps:
      - name: Build Project
        run: make build

  test:
    needs: build
    steps:
      - name: Run Tests
        run: make test

